### ISSUE TITLE
[Markdocs Server Error]: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by mmacy** [microsoft/vscode-docs-authoring#101]
After updating VS Code, I typically see some version of the following exception upon first launch after update. Here's the latest after my update to VS Code v1.72.2 today:

```
[Markdocs Server Error]: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Net.HttpEndPointListener.ProcessAccept(SocketAsyncEventArgs args)
   at System.Net.HttpEndPointListener.Accept(SocketAsyncEventArgs e)
   at System.Net.HttpEndPointListener..ctor(HttpListener listener, IPAddress addr, Int32 port, Boolean secure)
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at MarkdocsService.MarkdownHttpServer.Start() in C:\projects\markdocs-server\MarkdownHttpServer.cs:line 32
   at MarkdocsService.Program.HandleRequest() in C:\projects\markdocs-server\Program.cs:line 26
   at MarkdocsService.Program.Main(String[] args) in C:\projects\markdocs-server\Program.cs:line 14
```

The output window displays the following prior to the Markdocs server error popups:

```
Installing docs preview extension's dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package "docs-previewService for Linux (x64)" (26101 KB) .................... Done!

Installing package "docs-previewService for Linux (x64)"

Finished
```

## Environment

**OS:** Ubuntu 18.04 LTS
**VSCode version:** 1.72.2
**Docs extension versions**:
![image](https://user-images.githubusercontent.com/13394541/45827546-7ef1b780-bcab-11e8-8ae7-a6120c650e0d.png)

**Comment by jamarw** [comment]
Hi @mmacy , looping in @qinezh for assistance.  Thanks

**Comment by qinezh** [comment]
@mmacy Can you please try the latest version of docs-preview and see whether the issue still exists?

**Comment by mmacy** [comment]
Hi @qinezh,

After hitting the _Reload_ button for docs-preview **0.3.14**, the same exception appeared:

```
[Markdocs Server Error]: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Net.HttpEndPointListener.ProcessAccept(SocketAsyncEventArgs args)
   at System.Net.HttpEndPointListener.Accept(SocketAsyncEventArgs e)
   at System.Net.HttpEndPointListener..ctor(HttpListener listener, IPAddress addr, Int32 port, Boolean secure)
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at MarkdocsService.MarkdownHttpServer.Start() in C:\projects\markdocs-server\MarkdownHttpServer.cs:line 32
   at MarkdocsService.Program.HandleRequest() in C:\projects\markdocs-server\Program.cs:line 26
   at MarkdocsService.Program.Main(String[] args) in C:\projects\markdocs-server\Program.cs:line 14
```

Screenshot of post-install output:

![image](https://user-images.githubusercontent.com/13394541/46742261-84fc0800-cc5b-11e8-95d7-c869e92cbb92.png)

Current versions of all docs* extensions:

![image](https://user-images.githubusercontent.com/13394541/46742415-d3a9a200-cc5b-11e8-886d-c97b9cd35ddf.png)

**Comment by qinezh** [comment]
ok, I'll find a linux environment to do some investigation these days, thanks for the details.

**Comment by mmacy** [comment]
@qinezh Sounds good, thanks. Feel free to let me know if there's any way I can help.

**Comment by qinezh** [comment]
Hi @mmacy , can you please try the [latest version](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-preview) to see whether the issue has already been fixed.

**Comment by mmacy** [comment]
Sorry @qinezh, the exception is still thrown in the latest version.

```
[Markdocs Server Error]: 
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Net.HttpEndPointListener.ProcessAccept(SocketAsyncEventArgs args)
   at System.Net.HttpEndPointListener.Accept(SocketAsyncEventArgs e)
   at System.Net.HttpEndPointListener..ctor(HttpListener listener, IPAddress addr, Int32 port, Boolean secure)
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at MarkdocsService.MarkdownHttpServer.Start() in C:\projects\markdocs-server\MarkdownHttpServer.cs:line 32
   at MarkdocsService.Program.HandleRequest() in C:\projects\markdocs-server\Program.cs:line 26
   at MarkdocsService.Program.Main(String[] args) in C:\projects\markdocs-server\Program.cs:line 14
```

Error notifications on first launch after update:

![image](https://user-images.githubusercontent.com/13394541/49761399-d6387000-fc7b-11e8-8c45-138b348844bc.png)

Versions:

![image](https://user-images.githubusercontent.com/13394541/49761408-dc2e5100-fc7b-11e8-927b-4ba0c0cee8d0.png)

**Comment by qinezh** [comment]
I just tried from my Ubuntu virtual machine, it looks good to run it:

![image](https://user-images.githubusercontent.com/15644078/49775469-47872a00-fd33-11e8-8ed3-1e6be36ba3dc.png)


Can you please do below steps to help troubleshoot it?

1. download the packages: `wget https://github.com/qinezh/markdocs-server/releases/download/v1.0.18/netcore.zip`
2. unzip it: `unzip netcore.zip -d netcore`
3. run it with dotnet cli: `dotnet netcore/MarkdocsService.dll`

Does it throw the same exception on you machine?

**Comment by mmacy** [comment]
@qinezh No, the exception is not thrown when executing the service in this manner:

```console
marsh@marsh:~/Downloads$ dotnet netcore/MarkdocsService.dll 
Start...
```

I get the exception on two different Ubuntu machines, so there must be some other issue contributing to the nullref when launching in a full desktop scenario.

**Comment by mmacy** [comment]
Unsure whether this is any help, but if I run the version in the extension directory, I get this:

```console
marsh@marsh:~$ dotnet ~/.vscode/extensions/docsmsft.docs-preview-0.3.16/.markdocs/MarkdocsService.dll

Unhandled Exception: System.Net.HttpListenerException: Address already in use
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at MarkdocsService.MarkdownHttpServer.Start() in C:\projects\markdocs-server\MarkdownHttpServer.cs:line 32
   at MarkdocsService.Program.HandleRequest() in C:\projects\markdocs-server\Program.cs:line 26
   at MarkdocsService.Program.Main(String[] args) in C:\projects\markdocs-server\Program.cs:line 14
Aborted (core dumped)
```

**Comment by qinezh** [comment]
@mmacy Appreciate your help, I'll try to repro it in a full Ubuntu desktop as you mentioned and let you know if any updates.

**Comment by qinezh** [comment]
@ijash Are you getting this error in Ubuntu or other operation system?

**Comment by ijash** [comment]
@qinezh in linux mint 19.1, which derivatives of ubuntu 18.04

**Comment by bharney0** [comment]
docs-preview has substantially changed in the code base and now uses markdown-it extension based on built-in preview from VS Code. Closing this issue out due to the changes made to docs-preview no longer using this code.

**Comment by mmacy** [comment]
@bharney0 I can confirm that I've not seen this error in quite some time. Thanks!
