### ISSUE TITLE
Markdown linting error for DOCSMD004

### ISSUE THREAD

**Issue by bharney0** [microsoft/vscode-docs-authoring#450]
When opening a new file like changelog.md in docs-markdown project, error message shows in markdownlint output window.
```
[9:37:02 AM] ERROR: Exception while linting:
Error: Name 'DOCSMD004' of custom rule at index 11 is already used as a name or tag.
	at c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:58660
	at Array.forEach (<anonymous>)
	at c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:58594
	at Array.forEach (<anonymous>)
	at c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:58078
	at g (c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:58927)
	at Function.x.sync (c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:60531)
	at E (c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:47962)
	at A (c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:48514)
	at Timeout._onTimeout (c:\Users\bharn\.vscode\extensions\davidanson.vscode-markdownlint-0.34.0\bundle.js:1:51967)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
```

[AB#263266](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/263266)

**Comment by seesharprun** [comment]
Did you ever figure out what caused this error? I spun up a new Windows 10 box and installed the Docs Authoring Pack. Getting this exact same error and it's capturing the cursor every time I try to type.

**Comment by bharney0** [comment]
@seesharprun Thank you for reporting that you are experiencing this issue. We will look into this further.

**Comment by seesharprun** [comment]
The error is no longer occurring for me. You can re-close.
